In [67]:
import numpy as np
import math

In [68]:
# Divisao de um array

A = [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
print(A)
print(A[:int(len(A)/2)])
print(A[int(len(A)/2):])

B = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(B)
print(B[:int(len(B)/2)])
print(B[int(len(B)/2):])

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[10, 9, 8, 7, 6]
[5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4]
[5, 6, 7, 8, 9]


In [69]:
# Criando a funcao merge

begin = 0
middle = int(len(A)/2)
end = len(A)

left = A[begin:middle] + [math.inf]
right = A[middle:end] + [math.inf]
print(left)
print(right)

[10, 9, 8, 7, 6, inf]
[5, 4, 3, 2, 1, inf]


In [5]:
def merge(A, L, R):
    i = j = k = 0
    while i < len(L) and j < len(R):
        if L[i] < R[j]:
            A[k] = L[i]
            i += 1
        else:
            A[k] = R[j]
            j += 1
        k += 1
        
    while i < len(L):
        A[k] = L[i]
        i += 1
        k += 1
        
    while j < len(R):
        A[k] = R[j]
        j += 1
        k += 1

In [6]:
def merge_sort(A):    
    if len(A) > 1:
        q = len(A)//2            # Divisao inteira
        L = A[:q]
        R = A[q:]       
        
        merge_sort(L)
        merge_sort(R)
        merge(A, L, R)
    return A

In [8]:
K = [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 70, -12, 7, 14, 5, 81, 0, 800, -764,9,8,-5,6,3,-77,8,99]
print(K)
merge_sort(K)
print(K)

[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 70, -12, 7, 14, 5, 81, 0, 800, -764, 9, 8, -5, 6, 3, -77, 8, 99]
[-764, -77, -12, -5, 0, 3, 5, 6, 7, 8, 8, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 14, 70, 81, 99, 800]


In [32]:
import pandas as pd
data = pd.read_csv('instancias-num/num.1000.1.in')
arr = data.to_numpy().ravel()
print(len(arr))


1000


In [4]:
lista = [1,2,"a","b","c",3,4,5,6]
print(lista[3:])
print(lista[:3])


['b', 'c', 3, 4, 5, 6]
[1, 2, 'a']


## Algoritmo Counting sort

1. Encontra o maior valor da lista a ser ordenada
   [8, 10, 12, 4, 7, 3, 0] maior = 12
   
2. Cria um array para contagem com maior+1 posições

In [63]:
# Encontrando o maximo e minimo valor em uma lista:
a = [1, -2, 2, 0, 3, 4, 5, 10, -3, -1]
print('Maior valor da lista: ', max(a))
print('Menor valor da lista: ', min(a))

Maior valor da lista:  10
Menor valor da lista:  -3


In [64]:
# Criar uma lista de tamanho fixo inicializado com 0:
contador = max(a) + abs(min(a)) + 1
pos_zero = abs(min(a))

lista_contador = [0]*contador
print('Lista contador:   ', lista_contador)
print('Lista de indices: ', [i for i in range(min(a),max(a)+1)])

Lista contador:    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Lista de indices:  [-3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [65]:
# Incrementar as posicoes de lista_contador com os elementos da lista a ser ordenada
for i in range(len(a)):
    if a[i] == 0:
        lista_contador[pos_zero] += 1
    elif a[i] > 0:
        lista_contador[pos_zero + a[i]] += 1
    elif a[i] < 0:
        lista_contador[pos_zero + a[i]] += 1
    
        
print('Lista contador:   ', lista_contador)
print('Lista de indices: ', [i for i in range(min(a),max(a)+1)])        

Lista contador:    [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1]
Lista de indices:  [-3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [67]:
# Ler a lista_contador e gerar a lista ordenada
ordenada = []
for i in range(len(lista_contador)):
    if lista_contador[i] > 0:
        for j in range(lista_contador[i]):
            if i < pos_zero:
                ordenada += [i - pos_zero]
            elif i == pos_zero:
                ordenada += [0]
            elif i > pos_zero:
                ordenada += [i - pos_zero]
        
ordenada

[-3, -2, -1, 0, 1, 2, 3, 4, 5, 10]

In [18]:
# Criando a funcao counting sort:
def counting_sort(a):
    ordenada = []
    contador = max(a) + abs(min(a)) + 1
    pos_zero = abs(min(a))
    lista_contador = [0]*contador
    for i in range(len(a)):
        if a[i] == 0:
            lista_contador[pos_zero] += 1
        else:
            lista_contador[pos_zero + a[i]] += 1
    for i in range(len(lista_contador)):
        if lista_contador[i] > 0:
            for j in range(lista_contador[i]):
                if i == pos_zero:
                    ordenada += [0]
                else:
                    ordenada += [i - pos_zero]
    return ordenada    

In [71]:
# Testando counting sort:
print(counting_sort(a))

[-3, -2, -1, 0, 1, 2, 3, 4, 5, 10]


## Algoritmo Radix Sort

In [3]:
import math
a = [1000, 100, 10, 1, -1, -10, -10, -100, -1000, -10000]

# Calculando a quantidade de digitos do maior numero da lista em termos absolutos
menor = abs(min(a))
maior = abs(max(a))
digitos_menor = int(math.log10(menor)) +1
digitos_maior = int(math.log10(maior)) +1
print('Numero de digitos do menor numero: ', digitos_menor)
print('Numero de digitos do maior numero: ', digitos_maior)

Numero de digitos do menor numero:  5
Numero de digitos do maior numero:  4


In [63]:
# Transformando um numero em uma lista com os seus digitos
# Entrada: numero inteiro, Saida: lista de numeros inteiros
def number_to_list(num):
    negative = False
    res = []
    for x in str(num):
        if x == '-':
            negative = True
            continue
        if negative == True:
            res += [int(x)*-1]
            negative = False
            continue
        res += [int(x)]
    return res
number_to_list(-1000)

[-1, 0, 0, 0]

In [46]:
lista = [-1, 0, 0, 0]
len_maior = 10

for x in range(0, len_maior - len(lista)):
    lista = [0] + lista
lista

[0, 0, 0, 0, 0, 0, -1, 0, 0, 0]

In [56]:
import pandas as pd

a_row = pd.Series(lista)
index = [x for x in range(len(lista))]
df = pd.DataFrame(columns=index)
df = df.append(a_row, ignore_index=True)
df

0  1  2  3  4  5   6  7  8  9
0  0  0  0  0  0  0  -1  0  0  0

In [5]:
import math
def largest_digit_number(a):
    menor = abs(min(a))
    maior = abs(max(a))
    digitos_menor = int(math.log10(menor)) +1
    digitos_maior = int(math.log10(maior)) +1
    return digitos_maior if digitos_maior > digitos_menor else digitos_menor
#largest_digit_number(a)

In [64]:
def list_to_row(num, largest_digit_number, index=1 ):
    list = number_to_list(num)
    for x in range(0, (largest_digit_number+1) - len(list)):
        list = [0] + list
    list[0] = index
    return list
list_to_row(-1000, 6) # Primeiro numero da lista é o índice da lista a ser ordenada e que vai servir de hash

[1, 0, 0, -1, 0, 0, 0]

In [65]:
def list_to_matrix(a):
    matrix = []
    largest = largest_digit_number(a)
    for i in range(len(a)):
        matrix += [list_to_row(a[i], largest, i )]
    return matrix

In [66]:
list_to_matrix(a)

[[0, 0, 1, 0, 0, 0],
 [1, 0, 0, 1, 0, 0],
 [2, 0, 0, 0, 1, 0],
 [3, 0, 0, 0, 0, 1],
 [4, 0, 0, 0, 0, -1],
 [5, 0, 0, 0, -1, 0],
 [6, 0, 0, 0, -1, 0],
 [7, 0, 0, -1, 0, 0],
 [8, 0, -1, 0, 0, 0],
 [9, -1, 0, 0, 0, 0]]

In [75]:
import numpy as np
arr2D = np.array(list_to_matrix(a))
print(arr2D)
arr2D = arr2D[arr2D[:, -1].argsort()] # Ordenando a ultima coluna da matriz
print(arr2D)

[[ 0  0  1  0  0  0]
 [ 1  0  0  1  0  0]
 [ 2  0  0  0  1  0]
 [ 3  0  0  0  0  1]
 [ 4  0  0  0  0 -1]
 [ 5  0  0  0 -1  0]
 [ 6  0  0 -1  0  0]
 [ 7  0 -1  0  0  0]
 [ 8 -1  0  0  0  0]]
[[ 4  0  0  0  0 -1]
 [ 0  0  1  0  0  0]
 [ 1  0  0  1  0  0]
 [ 2  0  0  0  1  0]
 [ 5  0  0  0 -1  0]
 [ 6  0  0 -1  0  0]
 [ 7  0 -1  0  0  0]
 [ 8 -1  0  0  0  0]
 [ 3  0  0  0  0  1]]


In [88]:
def sorted_matrix(a):
    arr2D = np.array(list_to_matrix(a))
    for i in range(1, largest_digit_number(a)+1):
        arr2D = arr2D[arr2D[:, -i].argsort()]
    return arr2D
sm = sorted_matrix(a)
sm

array([[ 9, -1,  0,  0,  0,  0],
       [ 8,  0, -1,  0,  0,  0],
       [ 7,  0,  0, -1,  0,  0],
       [ 5,  0,  0,  0, -1,  0],
       [ 6,  0,  0,  0, -1,  0],
       [ 4,  0,  0,  0,  0, -1],
       [ 3,  0,  0,  0,  0,  1],
       [ 2,  0,  0,  0,  1,  0],
       [ 1,  0,  0,  1,  0,  0],
       [ 0,  0,  1,  0,  0,  0]])

In [84]:
index = []
for i in range(len(sm)):
    index += [sm[i][0]]
index

[8, 7, 6, 5, 4, 3, 2, 1, 0]

In [114]:
def radix_sort(a):
    sorted_list = []
    radix_matrix = sorted_matrix(a)
    for i in range(len(radix_matrix)):
        sorted_list += [a[radix_matrix[i][0]]]
    return sorted_list
radix_sort(a)

[-10000, -1000, -100, -10, -10, -1, 1, 10, 100, 1000]

In [115]:
arr[:20]

array([93287,    -2, 94656,   -29,   -14,    24,   -48,     8, 55486,
       83534, 67567,    15,    22,   -24,   -30, 50712,   -33, 84648,
       52274,    39])

In [60]:
list_to_matrix(arr[:20])

NameError: name 'list_to_matrix' is not defined

In [67]:
sorted_matrix(arr[:20])

NameError: name 'sorted_matrix' is not defined

In [12]:
import numpy as np

arr2D = np.array([[ 0,  9,  3,  2,  8,  7],
       [ 1,  0,  0,  0,  0, -2],
       [ 2,  9,  4,  6,  5,  6],
       [ 3,  0,  0,  0, -2,  9],
       [ 4,  0,  0,  0, -1,  4],
       [ 5,  0,  0,  0,  2,  4],
       [ 6,  0,  0,  0, -4,  8],
       [ 7,  0,  0,  0,  0,  8],
       [ 8,  5,  5,  4,  8,  6],
       [ 9,  8,  3,  5,  3,  4],
       [10,  6,  7,  5,  6,  7],
       [11,  0,  0,  0,  1,  5],
       [12,  0,  0,  0,  2,  2],
       [13,  0,  0,  0, -2,  4],
       [14,  0,  0,  0, -3,  0],
       [15,  5,  0,  7,  1,  2],
       [16,  0,  0,  0, -3,  3],
       [17,  8,  4,  6,  4,  8],
       [18,  5,  2,  2,  7,  4],
       [19,  0,  0,  0,  3,  9]])
#array2D_temp = arr2D
#col = {}
#array = arr2D[:,-1]

#for i in range(len(array)):
#    col[i] = array[i]

#col = {k: v for k, v in sorted(col.items(), key=lambda item: item[1])}

#list = [[]]*arr2D.shape[0]
#a = 0
#for i in col:
#    list[a] = arr2D[i].tolist()
#    a += 1
#list

for i in range(1, 6):
    radix_col = {}
    array = arr2D[:,-i]
    matrix = [[]]*arr2D.shape[0]
    a = 0
    for i in range(len(array)):
        radix_col[i] = array[i]
    radix_col = {k: v for k, v in sorted(radix_col.items(), key=lambda item: item[1])}
    for i in radix_col:
        matrix[a] = arr2D[i].tolist()
        a += 1
    arr2D = np.array(matrix)
arr2D

array([[ 6,  0,  0,  0, -4,  8],
       [14,  0,  0,  0, -3,  0],
       [16,  0,  0,  0, -3,  3],
       [13,  0,  0,  0, -2,  4],
       [ 3,  0,  0,  0, -2,  9],
       [ 4,  0,  0,  0, -1,  4],
       [ 1,  0,  0,  0,  0, -2],
       [ 7,  0,  0,  0,  0,  8],
       [11,  0,  0,  0,  1,  5],
       [12,  0,  0,  0,  2,  2],
       [ 5,  0,  0,  0,  2,  4],
       [19,  0,  0,  0,  3,  9],
       [15,  5,  0,  7,  1,  2],
       [18,  5,  2,  2,  7,  4],
       [ 8,  5,  5,  4,  8,  6],
       [10,  6,  7,  5,  6,  7],
       [ 9,  8,  3,  5,  3,  4],
       [17,  8,  4,  6,  4,  8],
       [ 0,  9,  3,  2,  8,  7],
       [ 2,  9,  4,  6,  5,  6]])

## Algoritmo Bucket Sort

In [18]:
bucket = [x for x in range(10)]
list_0 = [1, 12, 13, 14, 15]
bucket[0] = list_0
bucket
a = 16
bucket[0] += [a]
bucket

[[1, 12, 13, 14, 15, 16], 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
# Criando os buckets para a ordenacao (de 0 a 9 dividido entre numeros positivos e negativos)
bucket_positive = [x for x in range(10)]
bucket_negative = bucket_positive

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [59]:
def bucket_sort(a):
    bucket_length = 10
    bucket_positive = [[]]*bucket_length
    bucket_negative = [[]]*bucket_length
    ldn = largest_digit_number(a)
    num = 0.0
    res = []
    for i in range(len(a)):
        num = a[i]/math.pow(bucket_length,ldn-1)
        if num < 0:
            if not bucket_negative[int(abs(num))]:
                bucket_negative[int(abs(num))] = [a[i]]
            else: 
                bucket_negative[int(abs(num))] += [a[i]] 
        else:
            if not bucket_positive[int(abs(num))]:
                bucket_positive[int(abs(num))] = [a[i]]
            else: 
                bucket_positive[int(abs(num))] += [a[i]]
    for i in range(bucket_length):
        if bucket_negative[i]:
            bucket_negative[i] = counting_sort(bucket_negative[i])
        if bucket_positive[i]:
            bucket_positive[i] = counting_sort(bucket_positive[i])
    bucket_negative.reverse() 
    res = sum(bucket_negative, []) + sum(bucket_positive, [])
    return res
    
#bucket_sort([-2, -4, -8, -16])
bucket_sort(arr[:20])
        

[-48,
 -33,
 -30,
 -29,
 -24,
 -14,
 -2,
 8,
 15,
 22,
 24,
 39,
 50712,
 52274,
 55486,
 67567,
 83534,
 84648,
 93287,
 94656]

In [22]:
arr = [[]]*10
if not arr[0]:
    arr[0] = [14]
else:
    arr[0] += [14]
arr

arr[0] += [17]
if arr[0]:
    print("Exists!")

Exists!


[None, [], [], [], [], None, None, [], None, None]

In [57]:
k = [[8, 15, 22, 24, 39], [], [], [], [], [50712, 52274, 55486], [67567], [], [83534, 84648], [93287, 94656]]
res = []
for i in range(len(k)-1, 0, -1):
    if k[i]:
        res += k[i]
res

[93287, 94656, 83534, 84648, 67567, 50712, 52274, 55486]

## Heap Máximo

O valor de um nó é no máximo, igual ao valor de seu pai.

A[Parent(i)] >= A[i]

In [29]:
def parent(i):
    if i % 2 == 0:
        return (i // 2) -1
    return i // 2
    

def left(i):
    return 2*i + 1

def right(i):
    return 2*i + 2

def max_heapify(A, tamanho_heap, i):
    maior = 0
    l = left(i)
    r = right(i)
    
    if l < tamanho_heap and A[l] > A[i]:
        maior = l
    else:
        maior = i
    
    if r < tamanho_heap and A[r] > A[maior]:
        maior = r
        
    if maior != i:
        A[i], A[maior] = A[maior], A[i]
        max_heapify(A, tamanho_heap, maior)
        
def build_max_heap(A):
    for i in range(len(A)//2 -1, -1, -1):
        max_heapify(A, len(A), i)

In [30]:
def heap_sort(A):
    build_max_heap(A)
    for i in range(len(A)-1, 0, -1):
        A[i], A[0] = A[0], A[i]
        max_heapify(A, i, 0)

In [31]:
A = [16, 4, 10, 14, 7, 9, 3, 2, 8, 1]
heap_sort(A)
A

[1, 2, 3, 4, 7, 8, 9, 10, 14, 16]

In [33]:
heap_sort(arr)
arr

array([  -50,   -50,   -50,   -49,   -49,   -49,   -49,   -49,   -49,
         -49,   -48,   -48,   -48,   -48,   -48,   -48,   -48,   -48,
         -47,   -47,   -47,   -47,   -47,   -47,   -47,   -47,   -47,
         -46,   -46,   -46,   -46,   -46,   -45,   -45,   -45,   -45,
         -45,   -45,   -45,   -44,   -43,   -43,   -42,   -42,   -42,
         -42,   -42,   -41,   -41,   -41,   -41,   -41,   -40,   -40,
         -40,   -40,   -39,   -39,   -39,   -39,   -39,   -39,   -38,
         -38,   -38,   -38,   -38,   -38,   -37,   -37,   -37,   -37,
         -37,   -37,   -37,   -36,   -36,   -36,   -36,   -36,   -36,
         -36,   -36,   -35,   -35,   -34,   -34,   -34,   -34,   -33,
         -33,   -33,   -33,   -32,   -32,   -30,   -30,   -30,   -30,
         -30,   -30,   -30,   -29,   -29,   -29,   -29,   -29,   -29,
         -29,   -29,   -28,   -28,   -27,   -27,   -27,   -27,   -27,
         -26,   -26,   -26,   -26,   -25,   -25,   -25,   -25,   -25,
         -24,   -24,